[[Chuffed]]
arch = "aarch64"
git-tree-sha1 = "cd85f184ddd6bd20d837514169ccfd9ce8f00470"
os = "macos"

    [[Chuffed.download]]
    sha256 = "6c1773af227d775c8724060e23dd94f3950304c9b2d23408b3bf6fd9bab880d4"
    url = "https://github.com/JuliaBinaryWrappers/Chuffed_jll.jl/releases/download/Chuffed-v0.13.2+0/Chuffed.v0.13.2.aarch64-apple-darwin.tar.gz"
[[Chuffed]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "d40018bde4c34f84239b0e49e4062ff91987bf7e"
libc = "glibc"
os = "linux"

    [[Chuffed.download]]
    sha256 = "44ad258fa7924ca7a3a9540f22e91cea7aef7c4e10e385391d1d893d8944d9ec"
    url = "https://github.com/JuliaBinaryWrappers/Chuffed_jll.jl/releases/download/Chuffed-v0.13.2+0/Chuffed.v0.13.2.aarch64-linux-gnu-cxx03.tar.gz"
[[Chuffed]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a636a55b7e4a98ddc3869fe6b1ed7c6f50ffcead"
libc = "glibc"
os = "linux"

    [[Chuffed.download]]
    sha256 = "80545c06f2380a261ad638c8371f71e36049c7be871ad85625be092e8b14c5fd"
    url = "https://github.com/JuliaBinaryWrappers/Chuffed_jll.jl/releases/download/Chuffed-v0.13.2+0/Chuffed.v0.13.2.aarch64-linux-gnu-cxx11.tar.gz"
[[Chuffed]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "a8bccb39fb4d1f791b8b61fdde477dabd08cb3a4"
libc = "musl"
os = "linux"

    [[Chuffed.download]]
    sha256 = "e240fd1b68962ac2e5d536c335b3a44707d2ff2c86c530a638b074b1d0c5818f"
    url = "https://github.com/JuliaBinaryWrappers/Chuffed_jll.jl/releases/download/Chuffed-v0.13.2+0/Chuffed.v0.13.2.aarch64-linux-musl-cxx03.tar.gz"
[[Chuffed]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "fe99b6eef86887d97bac843df0540110cb7c3479"
libc = "musl"
os = "linux"

    [[Chuffed.download]]
    sha256 = "a5f09bda916169d214b2f534f10cdc9ee9bc98829eb55ea09766f2d64edfe047"
    url = "https://github.com/JuliaBinaryWrappers/Chuffed_jll.jl/releases/download/Chuffed-v0.13.2+0/Chuffed.v0.13.2.aarch64-linux-musl-cxx11.tar.gz"
[[Chuffed]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "e3662017165df9f76a1cd910dde795d4ee9b5a85"
libc = "glibc"
os = "linux"

    [[Chuffed.download]]
    sha256 = "e6d7a0c2a591b0f37b78fd9bd8e32994837e8fa12ada6f52c42a3a23b4a750c0"
    url = "https://github.com/JuliaBinaryWrappers/Chuffed_jll.jl/releases/download/Chuffed-v0.13.2+0/Chuffed.v0.13.2.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[Chuffed]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7e9ad7f3d6f8f8f041a9f47109f27e5e6c7aec5d"
libc = "glibc"
os = "linux"

    [[Chuffed.download]]
    sha256 = "1bd05f35dd5fd77f2ab9a6ed425cb2de6abc820a8d65af81506bf8215bc9bd19"
    url = "https://github.com/JuliaBinaryWrappers/Chuffed_jll.jl/releases/download/Chuffed-v0.13.2+0/Chuffed.v0.13.2.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[Chuffed]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "49c6926b339492af1c743e0495a0bceadab99efe"
libc = "musl"
os = "linux"

    [[Chuffed.download]]
    sha256 = "164d37ebf1ce38011e7a057b19bab4728017d0560a8ed650994352031f81c02a"
    url = "https://github.com/JuliaBinaryWrappers/Chuffed_jll.jl/releases/download/Chuffed-v0.13.2+0/Chuffed.v0.13.2.armv6l-linux-musleabihf-cxx03.tar.gz"
[[Chuffed]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "bdefb6549b62f4596d8d05a71f12c1af75af030c"
libc = "musl"
os = "linux"

    [[Chuffed.download]]
    sha256 = "798acc55c764fc311076012dc16f171a8bc587ea90c3e92e27f6f5912402a322"
    url = "https://github.com/JuliaBinaryWrappers/Chuffed_jll.jl/releases/download/Chuffed-v0.13.2+0/Chuffed.v0.13.2.armv6l-linux-musleabihf-cxx11.tar.gz"
[[Chuffed]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "5672cca4faa1ffae8bf97bcb7ef72e4232da0a22"
libc = "glibc"
os = "linux"

    [[Chuffed.download]]
    sha256 = "180d73947540a07a3a0eb867e4d25803d07b205703ed69ba519c0511758ebcc1"
    url = "https://github.com/JuliaBinaryWrappers/Chuffed_jll.jl/releases/download/Chuffed-v0.13.2+0/Chuffed.v0.13.2.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[Chuffed]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ae00aca40d196b28e1d2b6a43cff490d91397fd4"
libc = "glibc"
os = "linux"

    [[Chuffed.download]]
    sha256 = "52c382cdb64246b85bd9ac9ebd2d28124148078e666b3e0b279e846f4170c660"
    url = "https://github.com/JuliaBinaryWrappers/Chuffed_jll.jl/releases/download/Chuffed-v0.13.2+0/Chuffed.v0.13.2.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[Chuffed]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "18d9ca5c17c5b6e2f300798335b6e85815ef0a67"
libc = "musl"
os = "linux"

    [[Chuffed.download]]
    sha256 = "32795cb782a4f67f216e7484ba54755bf6140c1bbbe7f745a1e100dbcf8ef17e"
    url = "https://github.com/JuliaBinaryWrappers/Chuffed_jll.jl/releases/download/Chuffed-v0.13.2+0/Chuffed.v0.13.2.armv7l-linux-musleabihf-cxx03.tar.gz"
[[Chuffed]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5e85bf95f00d2f475af2556c26482794c733e126"
libc = "musl"
os = "linux"

    [[Chuffed.download]]
    sha256 = "cb30131900364d68d3b022e587c10dc94ac125c2ff7e7f81073896fe45fe2250"
    url = "https://github.com/JuliaBinaryWrappers/Chuffed_jll.jl/releases/download/Chuffed-v0.13.2+0/Chuffed.v0.13.2.armv7l-linux-musleabihf-cxx11.tar.gz"
[[Chuffed]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "3b4ef160c577816da88bc69cb6d426b3169e5d00"
libc = "glibc"
os = "linux"

    [[Chuffed.download]]
    sha256 = "8c3367d5e2d9d72cc492140d242005ff94b209a4b6b9d006d81b5129cfad9e5b"
    url = "https://github.com/JuliaBinaryWrappers/Chuffed_jll.jl/releases/download/Chuffed-v0.13.2+0/Chuffed.v0.13.2.i686-linux-gnu-cxx03.tar.gz"
[[Chuffed]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ddac01bf08c81b082957b1050924001e5d4899b3"
libc = "glibc"
os = "linux"

    [[Chuffed.download]]
    sha256 = "36d83481980a83e359d56cae9e7d193795fe22ed214df675a2817dcb816b5cdc"
    url = "https://github.com/JuliaBinaryWrappers/Chuffed_jll.jl/releases/download/Chuffed-v0.13.2+0/Chuffed.v0.13.2.i686-linux-gnu-cxx11.tar.gz"
[[Chuffed]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "45b1a9556cb25b31065dfbbb9ac9e970e0d18da8"
libc = "musl"
os = "linux"

    [[Chuffed.download]]
    sha256 = "891c93cb471841c4dae6866011043b9ca379127aa53bedd483d4b849978a4ce3"
    url = "https://github.com/JuliaBinaryWrappers/Chuffed_jll.jl/releases/download/Chuffed-v0.13.2+0/Chuffed.v0.13.2.i686-linux-musl-cxx03.tar.gz"
[[Chuffed]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "07425bdb9c152f46b53b5ffdc854e5181a764494"
libc = "musl"
os = "linux"

    [[Chuffed.download]]
    sha256 = "b5f998f259a76c27ad3559ecb12a326bc4f0cfc5521f34b6ac6bdc8ff99aa6b4"
    url = "https://github.com/JuliaBinaryWrappers/Chuffed_jll.jl/releases/download/Chuffed-v0.13.2+0/Chuffed.v0.13.2.i686-linux-musl-cxx11.tar.gz"
[[Chuffed]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "bc5705b9b09a6a42b9024541c63ae0298bb91129"
os = "windows"

    [[Chuffed.download]]
    sha256 = "863bd9fb56f547e383d556162091bbc2c5a1dbd3b9ee5503a5482a0e2e1fc039"
    url = "https://github.com/JuliaBinaryWrappers/Chuffed_jll.jl/releases/download/Chuffed-v0.13.2+0/Chuffed.v0.13.2.i686-w64-mingw32-cxx03.tar.gz"
[[Chuffed]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3ae55dd5c18c65ad0ef1721d80314b679e87ca14"
os = "windows"

    [[Chuffed.download]]
    sha256 = "e35a51b27aa8ac684bf150b0d4b4afd5b59a9d57404debf89788165f1503a5ff"
    url = "https://github.com/JuliaBinaryWrappers/Chuffed_jll.jl/releases/download/Chuffed-v0.13.2+0/Chuffed.v0.13.2.i686-w64-mingw32-cxx11.tar.gz"
[[Chuffed]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "3526a005ba4f15e064d331463ea64a602d0496d1"
libc = "glibc"
os = "linux"

    [[Chuffed.download]]
    sha256 = "ab60cec83181cb0dfa8c5a060ba2283f9412278b47be13a6957eb8d2f7e3c2b2"
    url = "https://github.com/JuliaBinaryWrappers/Chuffed_jll.jl/releases/download/Chuffed-v0.13.2+0/Chuffed.v0.13.2.powerpc64le-linux-gnu-cxx03.tar.gz"
[[Chuffed]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "06cf1bd93791485f8a198840deaa35b32273b6ee"
libc = "glibc"
os = "linux"

    [[Chuffed.download]]
    sha256 = "0ebedd9fc1aa53f365973d1e3a24df9b25dac5308ad2e09699af54d12ef65bd6"
    url = "https://github.com/JuliaBinaryWrappers/Chuffed_jll.jl/releases/download/Chuffed-v0.13.2+0/Chuffed.v0.13.2.powerpc64le-linux-gnu-cxx11.tar.gz"
[[Chuffed]]
arch = "x86_64"
git-tree-sha1 = "b8de1b4ca3684183ff6ed46d37c70396610754c4"
os = "macos"

    [[Chuffed.download]]
    sha256 = "06a19108de117e8d82a2ba6a2dc5deb7e0ca17c5b8c21a0117f65d873d17bc22"
    url = "https://github.com/JuliaBinaryWrappers/Chuffed_jll.jl/releases/download/Chuffed-v0.13.2+0/Chuffed.v0.13.2.x86_64-apple-darwin.tar.gz"
[[Chuffed]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "25faf27d12403664fcf33b05938d756e7e51b072"
libc = "glibc"
os = "linux"

    [[Chuffed.download]]
    sha256 = "31995263364821e287c0ba07fc136c478fb189d2db170764796e7bee608f24a5"
    url = "https://github.com/JuliaBinaryWrappers/Chuffed_jll.jl/releases/download/Chuffed-v0.13.2+0/Chuffed.v0.13.2.x86_64-linux-gnu-cxx03.tar.gz"
[[Chuffed]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e7edbcd52b7cb8d8504a7882ea44e00e55fca9b2"
libc = "glibc"
os = "linux"

    [[Chuffed.download]]
    sha256 = "c71ae26e0a6a7f7dd8721b9014b969fa48957ef2fa21ad4ed9052ea5e821693c"
    url = "https://github.com/JuliaBinaryWrappers/Chuffed_jll.jl/releases/download/Chuffed-v0.13.2+0/Chuffed.v0.13.2.x86_64-linux-gnu-cxx11.tar.gz"
[[Chuffed]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "22b3c9c64f912c25ceb653a49f8f64150b9db3af"
libc = "musl"
os = "linux"

    [[Chuffed.download]]
    sha256 = "b27b7919c7698a3ce2e76577ced2c2bc605af32d4a41b38353c0eab316d2570d"
    url = "https://github.com/JuliaBinaryWrappers/Chuffed_jll.jl/releases/download/Chuffed-v0.13.2+0/Chuffed.v0.13.2.x86_64-linux-musl-cxx03.tar.gz"
[[Chuffed]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4c3f53d3d0cca62ce52a682f930b3262f9f731a4"
libc = "musl"
os = "linux"

    [[Chuffed.download]]
    sha256 = "649d967d69761127bdc949412c1ae63c5fae0586c4a12f39e0d5e71c121b122e"
    url = "https://github.com/JuliaBinaryWrappers/Chuffed_jll.jl/releases/download/Chuffed-v0.13.2+0/Chuffed.v0.13.2.x86_64-linux-musl-cxx11.tar.gz"
[[Chuffed]]
arch = "x86_64"
git-tree-sha1 = "d56b76fae25fa4fef13799eb8ab24b4efda87727"
os = "freebsd"

    [[Chuffed.download]]
    sha256 = "fd11215892244fc0d261b96f239ff7903fc85f38aefa2e9d8ecf7f20fb5faeff"
    url = "https://github.com/JuliaBinaryWrappers/Chuffed_jll.jl/releases/download/Chuffed-v0.13.2+0/Chuffed.v0.13.2.x86_64-unknown-freebsd.tar.gz"
[[Chuffed]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "d4c79199f6060f62e7a661720593d274ed1e721d"
os = "windows"

    [[Chuffed.download]]
    sha256 = "8a8923b5ce0b9cef142a8f4f650d52432cbba7830222fdb917dbfbc408141ccd"
    url = "https://github.com/JuliaBinaryWrappers/Chuffed_jll.jl/releases/download/Chuffed-v0.13.2+0/Chuffed.v0.13.2.x86_64-w64-mingw32-cxx03.tar.gz"
[[Chuffed]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "69419d813da6e8af7cb4f9e4336d9b79882bf941"
os = "windows"

    [[Chuffed.download]]
    sha256 = "cd536b8083601f01b476f7513bcdfdb22d4db032c82b6fa2d21b8dea6a72736f"
    url = "https://github.com/JuliaBinaryWrappers/Chuffed_jll.jl/releases/download/Chuffed-v0.13.2+0/Chuffed.v0.13.2.x86_64-w64-mingw32-cxx11.tar.gz"
